<?php

namespace CodePress\CodeTag\Tests\Controller;

use CodePress\CodeTag\Controllers\TagController;
use CodePress\CodeTag\Controllers\Controller;
use CodePress\CodeTag\Models\Tag;
use CodePress\CodeTag\Tests\AbstractTestCase;
use Illuminate\Contracts\Routing\ResponseFactory;
use Mockery as m;

class TagControllerTest extends AbstractTestCase {

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->migrate();
    }

    public function test_should_extends_from_controller() {
        $tag = m::mock(Tag::class);
        $response = m::mock(ResponseFactory::class);
        $controller = new TagController($tag, $response);
        $this->assertInstanceOf(Controller::class, $controller);
    }

}
